## Introduction to Einstein Notation

This notation allows for expressing an extraordinary number of operations concisely. This section is not
necessary for the following but it is an interesting intellectual exercise.

The basic idea is to sum the terms of an equation when the same index appears twice and is not defined elsewhere. Thus:

$$ A_{i,i} \quad \textrm{means} \quad \sum_{i=1}^N A_{i,i} \; \textrm{(the trace of the matrix)}$$

If we look at the matrix multiplication $A\, B$, for every index (i,j) of the result we have:

$$ C_{i,j} = A_{i,k} \, B_{k,j} \quad \textrm{i.e.} \quad  C_{i,j} = \sum_{k=1}^N A_{i,k} \, B_{k,j} $$ 

The full name of the Einstein notation being the Einstein summation convention, the Numpy function is [`einsum`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.einsum.html). Here is how it works for our first 2 examples:

In [1]:
import numpy as np

A = np.arange(9).reshape(3,3)

print("Trace 'ii' : ", np.einsum('ii', A), '\n')   # 0 + 4 + 8 = 12

print("Multiplication matricielle A A 'ij,jk->ik' :")
print(np.einsum('ij,jk->ik', A, A))  # notez que j'ai nommé différement les indices

Trace 'ii' :  12 

Multiplication matricielle A A 'ij,jk->ik' :
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [2]:
A.dot(A)  # on vérifie

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

It is noted that the arguments of `einsum` are:

* the summation rule in a string with a comma to separate each component
* the components on which the rule applies

We can go a little further with Numpy. Here are all the rules that `einsum` uses:

#### Basic and additional rules

1. a repeated index implies summation over that index unless that index is mentioned in the result<br/>(see example of the diagonal of A below for the exception)
2. indices that repeat from one component to another imply that the referenced elements will be multiplied together<br/> (see example of the matrix product)
3. a letter omitted in the result (after `->`) implies summation over that index<br/> (see example of summing the elements of a vector below)
4. if you don't put the arrow, einsum will put it for you with on the right all the indices that are not doubled arranged in alphabetical order<br/> (see example of the transpose below)

Here is a list of operations taken from the [blog of Dr. Goulu](https://www.drgoulu.com/2016/01/17/einsum):

<table align="center">
<tbody>
<tr>
<th>einsum Signature</th>
<th>Numpy Equivalent</th>
<th>Description</th>
</tr>
<tr>
<td><code>('i-&gt;', v)</code></td>
<td><code>sum(v)</code></td>
<td>sum of values of vector v</td>
</tr>
<tr>
<td><code>('i,i-&gt;i', u, v)</code></td>
<td><code>u \* v</code></td>
<td>element-wise multiplication of vectors u and v</td>
</tr>
<tr>
<td><code>('i,i', u, v)</code></td>
<td><code>inner(u, v)</code></td>
<td>dot product of u and v</td>
</tr>
<tr>
<td><code>('i,j', u, v)</code></td>
<td><code>outer(u, v)</code></td>
<td>dyadic product of u and v</td>
</tr>
<tr>
<td><code>('ij', A)</code></td>
<td><code>A</code></td>
<td>returns matrix A</td>
</tr>
<tr>
<td><code>('ji', A)</code></td>
<td><code>A.T</code></td>
<td>transpose of A</td>
</tr>
<tr>
<td><code>('ii-&gt;i', A)</code></td>
<td><code>diag(A)</code></td>
<td>diagonal of A</td>
</tr>
<tr>
<td><code>('ii', A)</code></td>
<td><code>trace(A)</code></td>
<td>sum of the diagonal of A</td>
</tr>
<tr>
<td class="tg-031e"><code>('ij-&gt;', A)</code></td>
<td class="tg-031e"><code>sum(A)</code></td>
<td class="tg-031e">sum of values of A</td>
</tr>
<tr>
<td><code>('ij-&gt;j', A)</code></td>
<td><code>sum(A, axis=0)</code></td>
<td>sum of columns of A</td>
</tr>
<tr>
<td><code>('ij-&gt;i', A)</code></td>
<td><code>sum(A, axis=1)</code></td>
<td>sum of rows of A</td>
</tr>
<tr>
<td><code>('ij,ij-&gt;ij', A, B)</code></td>
<td><code>A \* B</code></td>
<td>element-wise transposed matrix multiplication of A and B</td>
</tr>
<tr>
<td><code>('ij,jk', A, B)</code></td>
<td><code>dot(A, B)</code></td>
<td>dot product of A and B</td> </tr>
<tr>
<td><code>('ij,jk-&gt;ij', A, B)</code></td>
<td><code>inner(A, B)</code></td>
<td>inner product of A and B</td>
</tr>
<tr>
<td><code>('ij,jk-&gt;ijk', A, B)</code></td>
<td><code>A[:, None] \* B</code></td>
<td>each row of A multiplied by B</td>
</tr>
<tr>
<td><code>('ij,kl-&gt;ijkl', A, B)</code></td>
<td><code>A[:, :, None, None] \* B</code></td>
<td>each value of A multiplied by B</td>
</tr>
</tbody>
</table>

The `None` in the last two lines is a way to reshape an array. So `np.arange(6)` is a 1-dimensional array, `np.arange(6)[:]` is the same 1-dimensional array, while `np.arange(6)[:,None]` is a 2-dimensional array namely `6 x 1` when `np.arange(6)[None,:,None]` has 3 dimensions: `1 x 6 x 1`.

## Practical Application

We will compare the performance of `einsum` and the corresponding Numpy functions. To do this, calculate

* the cube of each element of a vector
* of a square matrix, $A^3$,

with `einsum` and without. Compare the execution speed in all cases with 10000 elements.

In [3]:
# a vous de jouer









Solution :

In [4]:
u = np.random.random(10000)

%timeit u*u*u
%timeit np.einsum('i,i,i->i', u,u,u)

11.5 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
15.2 µs ± 131 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
A = u.reshape(100,100)

%timeit A.dot(A).dot(A)
%timeit np.einsum('ij,jk,kl->il', A, A, A)

138 µs ± 9.48 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
134 ms ± 1.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


We observe that `einsum` is slower (\*). But looking on the web, we see that this has not always been the case and that it is related to the version of the Numpy library. In conclusion, if we want performance, we should test our code beforehand to choose the fastest method.

(\*) slightly slower for vector calculation but 1000 times slower on my laptop for `A.dot(A)` (all my processors are running at 100% while the calculation by `einsum` is only done on 1 processor). The `A.dot(A)` version is much faster thanks to the MKL library used by Numpy on my machine.